services:
  fastauth:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://fastauth:fastauth@postgres:5432/fastauth
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=fastauth
      - POSTGRES_USER=fastauth
      - POSTGRES_PASSWORD=fastauth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastauth -d fastauth"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
